global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dnse-backend'
    static_configs:
      - targets: ['backend:9090']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
